### ISSUE TITLE
Mermaid Diagram Renders as Raster Image Instead of Expected SVG in PDF Output

### ISSUE THREAD

**Issue by SmartLayer** [oxygenxml/dita-ot-diagrams-plugin#11]
I have encountered an issue where the Mermaid diagram is rendered as a raster image instead of the expected SVG format in the PDF output. This is inconsistent with the documentation in the README, which states that the diagram should be in SVG format.

Steps to Reproduce:

1. Clone the repository from https://github.com/TokenScript/documents/
2. Checkout commit 42ed9788826c38f38ff83af486fbff9b39b059f8
3. Navigate to the src directory
4. Generate a PDF using the following command:
```
dita -i smartlayer-overview.ditamap -f pdf -o output
```
Expected Result:

The generated PDF (output/smartlayer-overview.pdf) should contain the Mermaid diagram in SVG format.

Actual Result:

The generated PDF contains the Mermaid diagram in raster image format.
![image](https://github.com/oxygenxml/dita-ot-diagrams-plugin/assets/548435/ba08fd96-0aa0-4351-b5eb-6dd1084ffd3d)

It's worth noting that this issue is less severe than issue #10, as a diagram is produced in this case, albeit in an incorrect format. Any assistance in resolving this discrepancy would be greatly appreciated.

**Comment by raducoravu** [comment]
@weiwu-zhang at some point I took the decision to embed the diagram as a binary image for the PDF output: https://github.com/oxygenxml/dita-ot-diagrams-plugin/commit/355f3b9a49bd6aa29fe433521e0d5da9138c8053
I'm afraid I forgot the reason for this change I made, I think it was because the generated SVG file in certain cases was not supported by the PDF engine so I decided to produce a binary image instead.

If you want you can try to revert the changes in the "pdfSVG.xsl" and generate it again as an SVG.
I just updated the readme to state that for mermaid images, the binary image is stored inside the PDF instead of the SVG.

**Comment by frankie-zeng** [comment]
@raducoravu how about https://mermaid.ink/#PDF%20output%20options,  can we embed the pdf into DITA output pdf?

**Comment by raducoravu** [comment]
@frankie-zeng so your question is about the possibility to generate using Mermaid a PDF image and then embed this PDF image in the final PDF, right?
This might work but it would need to be tested by making changes to the XSLT stylesheets from the plugin.
Are you generating the PDF using the standard XSL-FO based PDF processing plugin bundled with the DITA OT or the CSS-based approach using the Oxygen Chemistry processor?

**Comment by frankie-zeng** [comment]
Thanks for the quick reply, I am using statnd DITA OT pdf format.

**Comment by raducoravu** [comment]
@frankie-zeng maybe you can try installing the plugin and making changes to the XSLT stylesheet:
https://github.com/oxygenxml/dita-ot-diagrams-plugin/blob/master/com.oxygenxml.diagrams.svg/xsl/pdfSVG.xsl
so that the URL contains the proper path which would return a PDF image.
Apache FOP supports referencing PDF images:
https://xmlgraphics.apache.org/fop/fop-pdf-images.html

**Comment by frankie-zeng** [comment]
@raducoravu I change the `img` to `pdf`, but it use one full page.. 

![Image](https://github.com/user-attachments/assets/ad28126c-5a98-4639-89d1-3ee6b2618e98)

could you guide me how to fix it.

**Comment by raducoravu** [comment]
@frankie-zeng I'm afraid I do not know how to help with this one. Maybe you can ask on an Apache FOP users list if you have control over how the PDF image is displayed, you can probably set width and height attributes on the <fo:external-graphic>.

**Comment by frankie-zeng** [comment]
got it. thanks.
